additional test changes for case 114; specific versions for icase/no-icase FSes

diff --git a/tests/test-caseguard-case b/tests/test-caseguard-case
--- a/tests/test-caseguard-case
+++ b/tests/test-caseguard-case
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 "$TESTDIR/hghave" caseguard || exit 80
-"$TESTDIR/hghave" casefs || exit 80
+"$TESTDIR/hghave" no-icasefs || exit 80
 
 echo '% case-sensitive filesystem test'
 hg init repo2
@@ -17,6 +17,20 @@ echo FOO > FOO
 echo Foo > Foo
 echo fOO > fOO
 hg add && echo '% collision in initial add'
+
+hg st
+
+hg add foo FOO && echo '% collision in argument list'
+
+echo '% case-sensitive override test'
+echo baz > baz
+hg add baz
+mv baz BAZ
+hg add -o BAZ || echo '% disable collision check failure'
+mv BAZ Baz
+hg add -o
+
+hg st
 
 cd ..
 rm -rf repo2
diff --git a/tests/test-caseguard-icase b/tests/test-caseguard-icase
--- a/tests/test-caseguard-icase
+++ b/tests/test-caseguard-icase
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 "$TESTDIR/hghave" caseguard || exit 80
+"$TESTDIR/hghave" icasefs || exit 80
 
 echo '% case-insensitive filesystem test'
 hg init repo1
@@ -24,12 +25,15 @@ mv FOO foo
 echo FO > FO
 hg add FO || echo '% false positive, partial filename match'
 
-# argument collision
-echo bar > bar
-echo BART > BART
-hg add bar BART || echo '% false positive, partial argument name match'
-mv BART BAR
-hg add bar BAR && echo '% collision in list of arguments'
+hg st
+
+echo '% case-insensitive override test'
+echo baz > baz
+hg add baz
+mv baz BAZ
+hg add -o BAZ || echo '% disable collision check failure'
+mv BAZ Baz
+hg add -o
 
 hg st
 
